project:
  type: website
  output-dir: docs

website:
  title: "Pseudo_Struct"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quarto/vault.qmd
        text: 개인정보보호        
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

