---
title: "중앙 로그관리 시스템"
description: "ELK Stack"
author: "BenKorea"
date: "2025-06-27"
date-modified: last-modified
categories: [ELK Stack]
---

## ELK Stack 설치

### 디렉토리 생성

```{r elk-mkdir, eval=FALSE, filename="bash"}
sudo mkdir -p ~/projects/elk
```

```{r vault-mkdir-sub, eval=FALSE, filename="bash"}
sudo mkdir -p ~/projects/elk/esdata ~/projects/elk/logstash ~/projects/elk/logstash/pipline
```

-   검증
```{r elk-mkdir-validation, eval=FALSE, filename="bash"}
sudo ls -ld ~/projects/elk ~/projects/elk/esdata ~/projects/elk/logstash ~/projects/elk/logstash/pipline
```

### docker-compose.yml 작성

```{r nano-yml, eval=FALSE, filename="bash"}
sudo nano projects/elk/docker-compose.yml
```

```{r docker-compose, eval=FALSE, filename="docker-compose.yml"}
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g   # (필요시 메모리 조정)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"      # Filebeat/Log 수신용
      - "9600:9600"      # Logstash API
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
```
